version: '3.8'

services:
  weather-service:
    build:
      context: ./weather_service
      dockerfile: Dockerfile
      network: host
    container_name: weather-service
    ports:
      - "8000:8000"
    volumes:
      - weather_logs:/var/log
    networks:
      - grafana-stack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: infyartifactory.jfrog.io/docker/prom/prometheus:v3.9.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - grafana-stack
    depends_on:
      - weather-service

  grafana:
    image: infyartifactory.jfrog.io/docker/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - grafana-stack
    depends_on:
      - prometheus
      - loki

  loki:
    image: infyartifactory.jfrog.io/docker/grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana-stack
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  alloy:
    image: infyartifactory.jfrog.io/docker/grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - weather_logs:/var/log
    command: run /etc/alloy/config.alloy --server.http.listen-addr=0.0.0.0:12345
    networks:
      - grafana-stack
    depends_on:
      - loki
    environment:
      - LOKI_URL=http://loki:3100
      - DOCKER_HOST=${DOCKER_HOST}

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  weather_logs:

networks:
  grafana-stack:
    driver: bridge
